### ISSUE TITLE
Should original value exactly match actual original value?

### ISSUE THREAD

**Issue by williamzelesny** [waltzofpearls/reckon#17]
Hi, 

Apologies if this is a stupid question. Should the original values reported by the prophet metrics match the actual original values as seen directly from prometheus?

Sorry about the camera shot, its all i can work with at the moment
![InkedPXL_20210812_131236051 MP_LI](https://user-images.githubusercontent.com/41495262/129203463-b196ce3d-4792-485f-a46d-c07f91f403b9.jpg)

Unsure if ill be able to get logs over but mainly just wondering if this is unexpected

Thanks!

**Comment by waltzofpearls** [comment]
Hey @williamzelesny, thanks for reporting this issue. I will take a look later today.

**Comment by williamzelesny** [comment]
It looks like upon restarting it, it grabs the first value for the metric from Prometheus and then that value becomes the original value from prophet (forever or an extended period of time)

**Comment by waltzofpearls** [comment]
@williamzelesny tl;dr at every prometheus scrape interval, reckon tries to find original and forecasted metrics with the scraping timestamp, so without refreshing the original data from prometheus, reckon can only find the latest original value from the last fetch, and that could be from 2 hours ago.

A longer version plus a chart to help understand:

- reckon scrapes prometheus on scheduled interval, by default it's every 2 hours
- prophet generates forecasted data as `yhat`, along with minimum and maximum possible values (uncertainty intervals) as `yhat_lower` and `yhat_upper`
- original metrics are historical data, and they could be from a few hours ago
- forecasted metrics are future data, they are computed from historical data (the originals)
- when prometheus scrapes reckon, it tries to find original and forecasted values using the scraping timestamp
- original data hasn't been refreshed for possibly a few hours, so the nearest data could be from 2 hours ago

```
         ^
         |            _____ original 1 ______
         |           /                       \ 
fetch metrics and    1--0--0--1--0--1--0--1...0
generate forecasts                              _____ forecasted 1 _____  
         |                                     /                        \ 
         |                                     1--1--0--1--1--0--1--0...1
         |                                        ^                 ^
prometheus scrapes                                |                 |
metrics from reckon                          original: 0       original: 0
         |                                 forecasted: 1     forecasted: 0
         |           
         |                                      ______ original 2 _____
         |                                     /                       \
fetch metrics and                              1--1--0--0--1--1--1--0...1
generate forecasts                                                        _____ forecasted 2 _____
         |                                                               /                        \
         |                                                               1--1--0--0--0--1--1--1...0
         |                                                                     ^              ^
prometheus scrapes                                                             |              |
metrics from reckon                                                       original: 1    original: 1
         |                                                              forecasted: 0  forecasted: 1
         |
         |------------------------------------------ time ------------------------------------------->
```

Ignore the original values since they are up-to-date, and pretty much useless. I will either remove it, or change the code to fetch the latest original metric on every prometheus scrape. I think it's a bit unnecessary, since you already have the original values from prometheus.

**Comment by williamzelesny** [comment]
Awesome, thanks for the explanation, I really appreciate it and understand now. Its interesting that the yhat_upper and yhat_lower's granularity is higher (very variable line) however if its calculating that off of the historical original's then unsure how that could be being that the original's value is so flat.

Would it be beneficial to be able to set the interval for scraping prometheus?

**Comment by waltzofpearls** [comment]
Scraping frequency is configurable with `SCHEDULE` env var. It defaults to `@every 120m`. For every 2 hours, reckon will fetch 2 hours of metrics data from prometheus, combine the new data into a larger set of data that's configurable with `ROLLING_WINDOW` (default: 72 hours), and then pass the data set to a model (eg. prophet) for training and forecasting. It will generate 2 hours of forecasted data, and predicted values will be returned to prometheus on every scrape.

Original data in the rolling window set is not a flat line, but because it doesn't have any most recent data, so before it gets refreshed at the next scheduled time, on every scrape, prometheus only receives the last original value from the end of rolling window set, and this is why the original data line is flat. It just keeps getting the same value over and over again. This doesn't mean the original data set has the same value.

If you prefer a more frequent scrape and training cycle, could try shortening `SCHEDULE` to something like `@every 30m`. I wouldn't recommend anything shorter than 10 minutes. Also, there are many factors can contribute to the quality of forecasted results. When feeding data set into the model, the larger the better, so keep the rolling window relatively big will help, but not too big, because the entire data set is kept in memory.

Play around with different settings. I will also add more docs in README for configuration.

**Comment by waltzofpearls** [comment]
Closing this issue.

Removed `original` metric from exported metrics in PR https://github.com/waltzofpearls/reckon/pull/20, and is part of [v0.2.0](https://github.com/waltzofpearls/reckon/releases/tag/v0.2.0) release.

In the following screenshot, I added the metric from prometheus as original, `yhat`, `yhat_upper` and `yhat_lower` from reckon as forecasted:

![Screen Shot 2021-08-31 at 11 48 55 PM](https://user-images.githubusercontent.com/965430/131625143-a88c02cf-30fb-4548-a7c4-2830251b8886.png)
